spring.application.name=football_field_management

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/FootballBooking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}



# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# File Upload (ngoài resources ?? build JAR không b? m?t file)
# Ví d?: D:/uploads/avatars
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
file.upload-dir=C:/uploads/avatars
#file.upload-dir=D:/uploads/avatars

# ===============================
# JWT Configuration
jwt.secret=MySuperPrivateJwtSecretKeyThatIsLongEnough1234567890!!!
jwt.expiration=86400000


# ===============================
# SQL Init (b?t n?u có schema.sql ho?c data.sql)
# ===============================
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

# ===============================
# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nguyenkhanh2561990@gmail.com
spring.mail.password=unlq kitm khec idjv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000




